### ISSUE TITLE
Empty headers not added to request

### ISSUE THREAD

**Issue by diegolesli** [luckymarmot/Paw-Issues#45]
Hello. 

For some reasons I am connecting to an API which requieres empty HTTP headers in the GET request. Paw only add the header to the request if it has some content, even with a single space. But in that case server validates the content and it is not my application. 

Now that he ability to include headers based on the checkbox on the left exists I do think they should be ignored if they are empty. 

Let me know if there is a more appropriate channel for this request. 

Thanks,

**Comment by mittsh** [comment]
@diegolesli thanks for the feedback! Yes Paw is ignoring empty value headers and adds a warning for it, as we thought so far this is a very unlikely (and potentially illegal behavior), but why not I think you may be right, and if a user explicitly wants to have an empty value header, it should be kept. We will do that in a future version of Paw.

Unfortunately, I do not have a workaround to suggest for know, as ignoring empty headers is currently the expected behavior. Sorry.

**Comment by mittsh** [comment]
@diegolesli just to keep you updated: we've fixed this on our development branch, this fix will be released as part of Paw 2.3.4 in a few days
